### ISSUE TITLE
Build React component hierarchy

### ISSUE THREAD

**Issue by otech47** [setlife-network/setblocks#4]
Use the [UIUX Flowchart](https://github.com/setlife-network/setblocks/blob/master/docs/Document_2018-11-06_14-23-35.pdf) as a basis

- Each team member will have an ID so we could have a route like `/team/member/:teamMemberId` that shows that team member's schedule for the week
- We need a route + component for scheduling your own Setblocks, and maybe even one for editing a specific Setblock. Each setblock will have it's own ID on the backend as well so something like `/schedule/edit/:setblockId`

Preliminary list of routes for #4:
- `/` - LandingPage
- `/team` - TeamPage
- `/team/:teamMemberId` - TeamMemberPage
- `/schedule` - SchedulePage, with today's day selected by default
- `/schedule/:dayOfWeek` - SchedulePage, with correct day selected. `dayOfWeek` will be an integer from 0 to 6 (0 = Monday, 6 = Sunday)
- `/schedule/edit/:setblockId` - SetblockDetailPage

**Comment by FedeMadoery** [comment]
Component hierarchy that we will to follow: 
[componentHerarchy.pdf](https://github.com/setlife-network/setblocks/files/2680813/componentHerarchy.pdf)

**Comment by otech47** [comment]
closed in #11
