### ISSUE TITLE
Deploy as a progressive web app

### ISSUE THREAD

**Issue by otech47** [setlife-network/setblocks#44]

**Comment by FedeMadoery** [comment]
Following the suggestion of Google Lighthouse, we need to improve:

1. Does not register a Service Worker.
2. Does not respond with a 200 when offline.
3. Does not provide fallback content when JavaScript is not available.
4. Does not redirect HTTP traffic to HTTPS.
5. Page load is not fast enough on 3G. (in production our bundle is gonna be way smaller, and it will be solved)
6. User will not be prompted to Install the Web App.
7. Is not configured for a custom splash screen.


Main Tasks:

- [x] Add a noscript tag
- [x] Implement a Service Worker
- [x] Create the Manifest.json

**Comment by FedeMadoery** [comment]
Things to keep in mind in the deploy time, these will help to improve and reach 100 points in PWA - Based on Google Lighthouse analysis

Page load is not fast enough on mobile networks
- Our page loads too slowly and is not interactive within 10 seconds. (In the production deployment this will be solved, the packages will be lighter)

Does not redirect HTTP traffic to HTTPS 
- (In production deploy this will be resolved)
